### ISSUE TITLE
TypeError: render() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by TheCrazyT** [TheCrazyT/roboschool#13]
Currently there is a problem.
Looks like pip on windows only installs version "0.9.4" of gym.
Guess people need to wait till there exist an updated version on pip.

**Comment by TheCrazyT** [comment]
Adding this link just for reference:
https://github.com/openai/gym/issues/11

**Comment by TheCrazyT** [comment]
nvm i'm stupid.
just need to do

> python -m pip install -U gym

"-U" was important

**Comment by SJM114514** [comment]
Hello，I am so cute
